#mips-linux-gnu-gcc -std=c99 -Wall -Wextra -O0 main.c bin_trie.c &&  qemu-mips -L /usr/mips-linux-gnu/ ./a.out
CC = mips-linux-gnu-gcc
CC_OPTS=-O0 \
		-Wextra \
		-std=c99 \
		-Wall \
		-Wshadow \
		-Wpointer-arith \
		-Wcast-align
		

SRCDIR=src
APPNAME = prefix.mips
EX_TARGET_DIR=$(EX_DIR)/target
src=$(addprefix $(SRCDIR)/, *.c)

run: $(APPNAME)
	qemu-mips -L /usr/mips-linux-gnu/ ./$(APPNAME)

$(APPNAME): $(src)
	$(CC) $(CC_OPTS) $(src) -o $(APPNAME)
	

.PHONY: clean
clean:
	rm -f $(APPNAME)